import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-provider-enrollment-revalidation-revenue-protection",
  "engine": "recovery",
  "title": "Provider Enrollment Revalidation Revenue Protection",
  "shortTitle": "Provider Enrollment Revalidation Revenue Protection",
  "tagline": "Prevent avoidable claim holds and terminations by governing payer enrollment, revalidation, ownership, and location changes.",
  "industry": "Provider Enrollment Operations",
  "buyer": "Health systems and provider groups",
  "uiPort": 4659,
  "apiPort": 5659,
  "accent": "#c2410c",
  "currency": "USD",
  "primaryOutcome": "Provider Enrollment Revalidation Revenue Protection converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect provider rosters, licenses, sanctions, ownership, locations, reassignment, payer applications, revalidation dates, claims holds, and payments in one accountable workflow. Prevent avoidable claim holds and terminations by governing payer enrollment, revalidation, ownership, and location changes.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Provider Enrollment Revalidation Revenue Protection evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("provider-master-registry","PER01","Provider master registry","Execute provider master registry using provider rosters, licenses, sanctions, ownership, locations, reassignment, payer applications, revalidation dates, claims holds, and payments.","Produce a governed provider master registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payer Enrollment","text","Provider / Payer Enrollment · Standard Case"],["caseReference","Provider master registry Reference","text","PER01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",727500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",880275],["domainDriver","Enrollment Event","select","Initial enrollment",["Initial enrollment","Revalidation","Change of information"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider master registry case","License credential monitoring case","Sanction exclusion screening case","Ownership disclosure tracking case","Practice location control case"]}),
feature("license-credential-monitoring","PER02","License credential monitoring","Execute license credential monitoring using provider rosters, licenses, sanctions, ownership, locations, reassignment, payer applications, revalidation dates, claims holds, and payments.","Produce a governed license credential monitoring decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payer Enrollment","text","Provider / Payer Enrollment · Standard Case"],["caseReference","License credential monitoring Reference","text","PER02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",727500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",880275],["domainDriver","Enrollment Event","select","Initial enrollment",["Initial enrollment","Revalidation","Change of information"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider master registry case","License credential monitoring case","Sanction exclusion screening case","Ownership disclosure tracking case","Practice location control case"]}),
feature("sanction-exclusion-screening","PER03","Sanction exclusion screening","Execute sanction exclusion screening using provider rosters, licenses, sanctions, ownership, locations, reassignment, payer applications, revalidation dates, claims holds, and payments.","Produce a governed sanction exclusion screening decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payer Enrollment","text","Provider / Payer Enrollment · Standard Case"],["caseReference","Sanction exclusion screening Reference","text","PER03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",727500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",880275],["domainDriver","Enrollment Event","select","Initial enrollment",["Initial enrollment","Revalidation","Change of information"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider master registry case","License credential monitoring case","Sanction exclusion screening case","Ownership disclosure tracking case","Practice location control case"]}),
feature("ownership-disclosure-tracking","PER04","Ownership disclosure tracking","Execute ownership disclosure tracking using provider rosters, licenses, sanctions, ownership, locations, reassignment, payer applications, revalidation dates, claims holds, and payments.","Produce a governed ownership disclosure tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payer Enrollment","text","Provider / Payer Enrollment · Standard Case"],["caseReference","Ownership disclosure tracking Reference","text","PER04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",727500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",880275],["domainDriver","Enrollment Event","select","Initial enrollment",["Initial enrollment","Revalidation","Change of information"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider master registry case","License credential monitoring case","Sanction exclusion screening case","Ownership disclosure tracking case","Practice location control case"]}),
feature("practice-location-control","PER05","Practice location control","Execute practice location control using provider rosters, licenses, sanctions, ownership, locations, reassignment, payer applications, revalidation dates, claims holds, and payments.","Produce a governed practice location control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payer Enrollment","text","Provider / Payer Enrollment · Standard Case"],["caseReference","Practice location control Reference","text","PER05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",727500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",880275],["domainDriver","Enrollment Event","select","Initial enrollment",["Initial enrollment","Revalidation","Change of information"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider master registry case","License credential monitoring case","Sanction exclusion screening case","Ownership disclosure tracking case","Practice location control case"]}),
feature("reassignment-management","PER06","Reassignment management","Execute reassignment management using provider rosters, licenses, sanctions, ownership, locations, reassignment, payer applications, revalidation dates, claims holds, and payments.","Produce a governed reassignment management decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payer Enrollment","text","Provider / Payer Enrollment · Standard Case"],["caseReference","Reassignment management Reference","text","PER06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",727500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",880275],["domainDriver","Enrollment Event","select","Initial enrollment",["Initial enrollment","Revalidation","Change of information"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider master registry case","License credential monitoring case","Sanction exclusion screening case","Ownership disclosure tracking case","Practice location control case"]}),
feature("payer-application-workflow","PER07","Payer application workflow","Execute payer application workflow using provider rosters, licenses, sanctions, ownership, locations, reassignment, payer applications, revalidation dates, claims holds, and payments.","Produce a governed payer application workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payer Enrollment","text","Provider / Payer Enrollment · Standard Case"],["caseReference","Payer application workflow Reference","text","PER07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",727500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",880275],["domainDriver","Enrollment Event","select","Initial enrollment",["Initial enrollment","Revalidation","Change of information"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider master registry case","License credential monitoring case","Sanction exclusion screening case","Ownership disclosure tracking case","Practice location control case"]}),
feature("revalidation-deadline-engine","PER08","Revalidation deadline engine","Execute revalidation deadline engine using provider rosters, licenses, sanctions, ownership, locations, reassignment, payer applications, revalidation dates, claims holds, and payments.","Produce a governed revalidation deadline engine decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payer Enrollment","text","Provider / Payer Enrollment · Standard Case"],["caseReference","Revalidation deadline engine Reference","text","PER08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",727500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",880275],["domainDriver","Enrollment Event","select","Initial enrollment",["Initial enrollment","Revalidation","Change of information"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider master registry case","License credential monitoring case","Sanction exclusion screening case","Ownership disclosure tracking case","Practice location control case"]}),
feature("pecos-data-comparison","PER09","PECOS data comparison","Execute pecos data comparison using provider rosters, licenses, sanctions, ownership, locations, reassignment, payer applications, revalidation dates, claims holds, and payments.","Produce a governed pecos data comparison decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payer Enrollment","text","Provider / Payer Enrollment · Standard Case"],["caseReference","PECOS data comparison Reference","text","PER09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",727500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",880275],["domainDriver","Enrollment Event","select","Initial enrollment",["Initial enrollment","Revalidation","Change of information"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider master registry case","License credential monitoring case","Sanction exclusion screening case","Ownership disclosure tracking case","Practice location control case"]}),
feature("roster-submission-tracking","PER10","Roster submission tracking","Execute roster submission tracking using provider rosters, licenses, sanctions, ownership, locations, reassignment, payer applications, revalidation dates, claims holds, and payments.","Produce a governed roster submission tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payer Enrollment","text","Provider / Payer Enrollment · Standard Case"],["caseReference","Roster submission tracking Reference","text","PER10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",727500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",880275],["domainDriver","Enrollment Event","select","Initial enrollment",["Initial enrollment","Revalidation","Change of information"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider master registry case","License credential monitoring case","Sanction exclusion screening case","Ownership disclosure tracking case","Practice location control case"]}),
feature("payer-response-remediation","PER11","Payer response remediation","Execute payer response remediation using provider rosters, licenses, sanctions, ownership, locations, reassignment, payer applications, revalidation dates, claims holds, and payments.","Produce a governed payer response remediation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payer Enrollment","text","Provider / Payer Enrollment · Standard Case"],["caseReference","Payer response remediation Reference","text","PER11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",727500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",880275],["domainDriver","Enrollment Event","select","Initial enrollment",["Initial enrollment","Revalidation","Change of information"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider master registry case","License credential monitoring case","Sanction exclusion screening case","Ownership disclosure tracking case","Practice location control case"]}),
feature("claim-hold-detection","PER12","Claim hold detection","Execute claim hold detection using provider rosters, licenses, sanctions, ownership, locations, reassignment, payer applications, revalidation dates, claims holds, and payments.","Produce a governed claim hold detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payer Enrollment","text","Provider / Payer Enrollment · Standard Case"],["caseReference","Claim hold detection Reference","text","PER12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",727500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",880275],["domainDriver","Enrollment Event","select","Initial enrollment",["Initial enrollment","Revalidation","Change of information"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider master registry case","License credential monitoring case","Sanction exclusion screening case","Ownership disclosure tracking case","Practice location control case"]}),
feature("at-risk-revenue-calculation","PER13","At-risk revenue calculation","Execute at-risk revenue calculation using provider rosters, licenses, sanctions, ownership, locations, reassignment, payer applications, revalidation dates, claims holds, and payments.","Produce a governed at-risk revenue calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payer Enrollment","text","Provider / Payer Enrollment · Standard Case"],["caseReference","At-risk revenue calculation Reference","text","PER13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",727500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",880275],["domainDriver","Enrollment Event","select","Initial enrollment",["Initial enrollment","Revalidation","Change of information"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider master registry case","License credential monitoring case","Sanction exclusion screening case","Ownership disclosure tracking case","Practice location control case"]}),
feature("enrollment-evidence-package","PER14","Enrollment evidence package","Execute enrollment evidence package using provider rosters, licenses, sanctions, ownership, locations, reassignment, payer applications, revalidation dates, claims holds, and payments.","Produce a governed enrollment evidence package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payer Enrollment","text","Provider / Payer Enrollment · Standard Case"],["caseReference","Enrollment evidence package Reference","text","PER14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",727500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",880275],["domainDriver","Enrollment Event","select","Initial enrollment",["Initial enrollment","Revalidation","Change of information"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider master registry case","License credential monitoring case","Sanction exclusion screening case","Ownership disclosure tracking case","Practice location control case"]}),
feature("provider-payer-analytics","PER15","Provider payer analytics","Execute provider payer analytics using provider rosters, licenses, sanctions, ownership, locations, reassignment, payer applications, revalidation dates, claims holds, and payments.","Produce a governed provider payer analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payer Enrollment","text","Provider / Payer Enrollment · Standard Case"],["caseReference","Provider payer analytics Reference","text","PER15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",727500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",880275],["domainDriver","Enrollment Event","select","Initial enrollment",["Initial enrollment","Revalidation","Change of information"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Provider master registry case","License credential monitoring case","Sanction exclusion screening case","Ownership disclosure tracking case","Practice location control case"]})
]);
